language: go

env:
- GO111MODULE=on

services:
- docker

go:
- 1.11.x
- master

notifications:
  email: false

before_script:
- go mod download
- GO111MODULE=off go get github.com/golangci/golangci-lint/cmd/golangci-lint

script:
- go test -v -race ./...
- golangci-lint run

after_success:
- GO111MODULE=off go get github.com/Clever/gitsem
- git config --global user.name "Ali Shanaakh"
- git config --global user.email "github@shanaakh.pro"
- gitsem -m "[ci skip] Bump version to %s" patch
- git remote add authenticated-origin https://$GITHUB_USER:$GITHUB_API_KEY@github.com/${TRAVIS_REPO_SLUG}
- git push --tags authenticated-origin HEAD:$TRAVIS_BRANCH
- docker login quay.io -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t quay.io/shal/robot:$(git describe --tags --abbrev=0) .
- docker push quay.io/shal/robot:$(git describe --tags --abbrev=0)
