log:
  level: "debug"
  mode:  "dev"

server:
  shutdown_timeout: "15s"
  read_timeout: "10s"
  write_timeout: "10s"
  idle_timeout: "10s"

autoria:
  api_key: "fuck_you"
  period: "1h"

database:
  host: "127.0.0.1"
  port:  5432
  username: "postgres"
  password: "password"
  database: "bot"
  ssl_mode: "disable"
